In [6]:
import pandas as pd

In [7]:
df = pd.read_csv('./data/partitions/wos_all.csv')

/var/folders/sf/ksfgwr354pl2gjdb_f0yn3vr0000gn/T/ipykernel_87711/2813474247.py:1: DtypeWarning: Columns (13,18,20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('./data/partitions/wos_all.csv')

In [8]:
df.head()

,Publication Type,Authors,Article Title,Language,Document Type,Author Keywords,Keywords Plus,Abstract,ORCIDs,Funding Orgs,...,Issue,Part Number,DOI,DOI Link,WoS Categories,Web of Science Index,Research Areas,IDS Number,Pubmed Id,UT (Unique WOS ID)
0,J,"Hughes, P",Regional intermediary actors and professionali...,English,Article,Community-led housing; collaborative housing; ...,LAND TRUSTS; SUSTAINABILITY; TRANSITIONS; WORK...,Community-led housing initiatives address hous...,"Hughes, Philippa/0009-0000-6285-8983",ESRC [ES/Y008138/1]; ESRC studentship at the U...,...,1,NaN,10.1080/02673037.2024.2439455,0.0,Environmental Studies; Regional & Urban Planni...,Social Science Citation Index (SSCI),Environmental Sciences & Ecology; Public Admin...,Q5305,NaN,WOS:001385022700001
1,J,"Koca, HU; Koca, SB; Jawad, LA",The developmental changes in the otolith morph...,English,Article,inter- and intraspecific variation; morphology...,INNER-EAR; TELEOSTEI CYPRINODONTIDAE; SAGITTA ...,Otoliths from four species of scorpaenids-Heli...,"Jawad, Laith/0000-0002-8294-2944;",Isparta University of Applied Sciences Scienti...,...,1,NaN,10.1111/azo.12532,0.0,Anatomy & Morphology; Zoology,Science Citation Index Expanded (SCI-EXPANDED),Anatomy & Morphology; Zoology,L6949,NaN,WOS:001389849900001
2,J,"Güclü, SS; Jawad, LA; Koca, HU; Cilbiz, M; Ayd...",Skeletal deformities in Sparus aurata from Tür...,English,Article,environment; mammography; sea bream; skeletal ...,SADDLEBACK-SYNDROME; OSTEOLOGICAL DEVELOPMENT;...,The first record of the abnormalities ankylosi...,"AYDIN, Celalettin/0000-0001-8993-6013; Jawad, ...",Scientific and Technological Research Council ...,...,1,NaN,10.1111/azo.12538,0.0,Anatomy & Morphology; Zoology,Science Citation Index Expanded (SCI-EXPANDED),Anatomy & Morphology; Zoology,L6949,NaN,WOS:001410940900001
3,J,"Alia, Z; Khechekhouche, E; Amara, DG; Messaoud...","Exploring diversity, abundance and ecological ...",English,Article,abundance variation; agriculture; diversity; i...,DAMAGE,The following subject provides an in-depth loo...,"Alia, Zeid/0000-0003-3184-9456; Sawicka, Barba...","King Saud University, Riyadh, Saudi Arabia; [R...",...,1.0,NaN,10.1111/azo.12539,0.0,Anatomy & Morphology; Zoology,Science Citation Index Expanded (SCI-EXPANDED),Anatomy & Morphology; Zoology,L6949,NaN,WOS:001416324100001
4,J,"Khan, S; Jawad, LA; Khan, MA; Park, JM; Bano, ...",The relationships between fish length and otol...,English,Article,Channidae; fish length; linear regression; mor...,BODY LENGTH; VALENCIENNES; MESSINA; STRAIT; GR...,The relationship between the total length of f...,"Jawad, Laith/0000-0002-8294-2944;","Council of Scientific and Industrial Research,...",...,1,NaN,10.1111/azo.12540,0.0,Anatomy & Morphology; Zoology,Science Citation Index Expanded (SCI-EXPANDED),Anatomy & Morphology; Zoology,L6949,NaN,WOS:001427492700001

In [ ]:
df[df["UT (Unique WOS ID)"] == "WOS:000556843900014"]

In [9]:
df[df['Article Title'].str.contains('Status of connected wetlands', case=False, na=False)]

,Publication Type,Authors,Article Title,Language,Document Type,Author Keywords,Keywords Plus,Abstract,ORCIDs,Funding Orgs,...,Issue,Part Number,DOI,DOI Link,WoS Categories,Web of Science Index,Research Areas,IDS Number,Pubmed Id,UT (Unique WOS ID)
1586769,J,"Pisanu, P; Kingsford, RT; Wilson, B; Bonifacio, R",Status of connected wetlands of the Lake Eyre ...,English,Article,ecosystem; IUCN Red List criteria; risk assess...,ARID-ZONE RIVERS; MURRAY-DARLING BASIN; SOIL S...,"The Lake Eyre Basin, one of the world's last u...","Kingsford, Richard/0000-0001-6565-4134",Australian Centre for Ecological Synthesis and...,...,4,NaN,10.1111/aec.12203,0.0,Ecology,Science Citation Index Expanded (SCI-EXPANDED),Environmental Sciences & Ecology,CJ1CG,NaN,WOS:000355218900011

In [ ]:
len(df)

In [ ]:
df.info()

In [ ]:
df.head()