In [11]:
import pandas as pd

In [12]:
df = pd.read_csv('../data/partitions/wos_all.csv')

In [13]:
df.head()

,Publication Type,Authors,Article Title,Language,Document Type,Author Keywords,Keywords Plus,Abstract,Publisher,Journal Abbreviation,Journal ISO Abbreviation,Publication Date,Publication Year,DOI,DOI Link,WoS Categories,Web of Science Index,Research Areas,Pubmed Id,UT (Unique WOS ID)
0,J,"Hughes, P",Regional intermediary actors and professionali...,English,Article,Community-led housing; collaborative housing; ...,LAND TRUSTS; SUSTAINABILITY; TRANSITIONS; WORK...,Community-led housing initiatives address hous...,"ROUTLEDGE JOURNALS, TAYLOR & FRANCIS LTD",HOUSING STUD,Hous. Stud.,JAN 2,2026,10.1080/02673037.2024.2439455,0.0,Environmental Studies; Regional & Urban Planni...,Social Science Citation Index (SSCI),Environmental Sciences & Ecology; Public Admin...,NaN,WOS:001385022700001
1,J,"Koca, HU; Koca, SB; Jawad, LA",The developmental changes in the otolith morph...,English,Article,inter- and intraspecific variation; morphology...,INNER-EAR; TELEOSTEI CYPRINODONTIDAE; SAGITTA ...,Otoliths from four species of scorpaenids-Heli...,WILEY,ACTA ZOOL-STOCKHOLM,Acta Zool.,JAN,2026,10.1111/azo.12532,0.0,Anatomy & Morphology; Zoology,Science Citation Index Expanded (SCI-EXPANDED),Anatomy & Morphology; Zoology,NaN,WOS:001389849900001
2,J,"Güclü, SS; Jawad, LA; Koca, HU; Cilbiz, M; Ayd...",Skeletal deformities in Sparus aurata from Tür...,English,Article,environment; mammography; sea bream; skeletal ...,SADDLEBACK-SYNDROME; OSTEOLOGICAL DEVELOPMENT;...,The first record of the abnormalities ankylosi...,WILEY,ACTA ZOOL-STOCKHOLM,Acta Zool.,JAN,2026,10.1111/azo.12538,0.0,Anatomy & Morphology; Zoology,Science Citation Index Expanded (SCI-EXPANDED),Anatomy & Morphology; Zoology,NaN,WOS:001410940900001
3,J,"Alia, Z; Khechekhouche, E; Amara, DG; Messaoud...","Exploring diversity, abundance and ecological ...",English,Article,abundance variation; agriculture; diversity; i...,DAMAGE,The following subject provides an in-depth loo...,WILEY,ACTA ZOOL-STOCKHOLM,Acta Zool.,JAN,2026,10.1111/azo.12539,0.0,Anatomy & Morphology; Zoology,Science Citation Index Expanded (SCI-EXPANDED),Anatomy & Morphology; Zoology,NaN,WOS:001416324100001
4,J,"Khan, S; Jawad, LA; Khan, MA; Park, JM; Bano, ...",The relationships between fish length and otol...,English,Article,Channidae; fish length; linear regression; mor...,BODY LENGTH; VALENCIENNES; MESSINA; STRAIT; GR...,The relationship between the total length of f...,WILEY,ACTA ZOOL-STOCKHOLM,Acta Zool.,JAN,2026,10.1111/azo.12540,0.0,Anatomy & Morphology; Zoology,Science Citation Index Expanded (SCI-EXPANDED),Anatomy & Morphology; Zoology,NaN,WOS:001427492700001

In [14]:
df[df['Article Title'].str.contains('Status of connected wetlands', case=False, na=False)]

,Publication Type,Authors,Article Title,Language,Document Type,Author Keywords,Keywords Plus,Abstract,Publisher,Journal Abbreviation,Journal ISO Abbreviation,Publication Date,Publication Year,DOI,DOI Link,WoS Categories,Web of Science Index,Research Areas,Pubmed Id,UT (Unique WOS ID)
1663589,J,"Pisanu, P; Kingsford, RT; Wilson, B; Bonifacio, R",Status of connected wetlands of the Lake Eyre ...,English,Article,ecosystem; IUCN Red List criteria; risk assess...,ARID-ZONE RIVERS; MURRAY-DARLING BASIN; SOIL S...,"The Lake Eyre Basin, one of the world's last u...",WILEY,AUSTRAL ECOL,Austral Ecol.,JUN,2015,10.1111/aec.12203,0.0,Ecology,Science Citation Index Expanded (SCI-EXPANDED),Environmental Sciences & Ecology,NaN,WOS:000355218900011

In [15]:
df.columns

Index(['Publication Type', 'Authors', 'Article Title', 'Language',
       'Document Type', 'Author Keywords', 'Keywords Plus', 'Abstract',
       'Publisher', 'Journal Abbreviation', 'Journal ISO Abbreviation',
       'Publication Date', 'Publication Year', 'DOI', 'DOI Link',
       'WoS Categories', 'Web of Science Index', 'Research Areas', 'Pubmed Id',
       'UT (Unique WOS ID)'],
      dtype='object')

In [16]:
len(df)

2414191

In [17]:
publication_year_ut_summary = (
    df.groupby('Publication Year')['UT (Unique WOS ID)']
    .agg(
        ut_count='count',
        ut_unique_count='nunique',
    )
    .reset_index()
    .sort_values('Publication Year')
)

publication_year_ut_summary

    Publication Year  ut_count  ut_unique_count
0               2000     23436            23436
1               2001     25524            25524
2               2002     26821            26821
3               2003     29249            29249
4               2004     31057            31057
5               2005     34031            34031
6               2006     38291            38291
7               2007     42273            42273
8               2008     46685            46685
9               2009     51384            51384
10              2010     55640            55640
11              2011     62212            62212
12              2012     66670            66670
13              2013     77328            77328
14              2014     83326            83326
15              2015     91376            91376
16              2016    102451           102451
17              2017    108002           108002
18              2018    117498           117498
19              2019    133391           133391
20              2020    151121           151121
21              2021    169384           169384
22              2022    182760           182760
23              2023    182067           182067
24              2024    195057           195057
25              2025    206913           206913
26              2026     80244            80244